name: Docker
on:
  pull_request:
    branches:
      - master

jobs:
  build_and_push_docker:
    permissions:
      packages: write
      contents: none
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@master


      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Build
        run: |
          export npm_config_target_platform=linux
          export EDITION=pro
          git submodule update --init
          yarn --force --ignore-engines --frozen-lockfile
          yarn run build --linux --prod --verbose
          yarn run package --linux
          cp build/docker/Dockerfile packages/bp/binaries/
      - name: DockerHub Authentication
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tiggomark/chatbot:latest
